inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/initializers/devise.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'spec/spec_helper.rb'
    - 'db/schema.rb'
    - 'db/**/*'
    - 'vendor/**/*'
