inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'config/initializers/*'
    - 'spec/spec_helper.rb'
    - 'db/schema.rb'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
